name: CI/CD Pipeline - BoardGame

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '18.x'
  PYTHON_VERSION: '3.10'

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy BoardGame to EC2 using Docker
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PROJECT_DIR: ${{ secrets.EC2_PROJECT_DIR }}
        run: |
          echo "🔐 Connecting to EC2 instance at $EC2_HOST"

          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            set -e

            echo "🚀 Starting deployment of BoardGame project..."

            # Use provided directory or fallback to home/app
            PROJECT_DIR="${EC2_PROJECT_DIR:-/home/$USER/app}"

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "📦 Cloning repository..."
              rm -rf "$PROJECT_DIR"
              git clone https://github.com/teamdev8/Boardgame.git "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"

            echo "🔄 Resetting and updating repository..."
            git reset --hard
            git clean -fd
            git pull origin main

            echo "🛑 Stopping existing containers..."
            docker compose down || true

            echo "🔨 Building Docker image..."
            docker compose build --no-cache

            echo "📦 Starting containers..."
            docker compose up -d

            echo "✅ Deployment complete."
          EOF

      - name: Cleanup SSH key
        run: rm -f key.pem
