name: CI/CD Pipeline - BoardGame

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '18.x'
  PYTHON_VERSION: '3.10'

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy BoardGame to EC2 using Docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PROJECT_DIR: ${{ secrets.EC2_PROJECT_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
            set -e

            echo "Deploying BoardGame project..."

            if [ ! -d "$EC2_PROJECT_DIR/.git" ]; then
              echo "Cloning BoardGame repository..."
              rm -rf "$EC2_PROJECT_DIR"
              git clone https://github.com/teamdev8/Boardgame.git "$EC2_PROJECT_DIR"
            fi

            cd "$EC2_PROJECT_DIR"

            echo "Pulling latest code from main branch..."
            git reset --hard
            git clean -fd
            git pull origin main

            echo "Stopping any running containers..."
            docker-compose down || true

            echo "Building Docker image without cache..."
            docker-compose build --no-cache

            echo "Starting Docker containers in detached mode..."
            docker-compose up -d

            echo "✅ BoardGame deployment complete."
          EOF

      - name: Cleanup SSH key
        run: rm -f key.pem
