name: CI/CD Pipeline - BoardGame

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .tar archive for deployment
        run: |
          tar -cvf boardgame-app.tar Dockerfile src/ pom.xml .mvn/ mvnw

      - name: Debug workspace
        run: ls -lah

      - name: Copy .tar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: boardgame-app.tar
          target: /home/ubuntu/app

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/app

            echo "Cleaning old files..."
            rm -rf boardgame
            mkdir boardgame

            echo "Extracting tar..."
            tar -xvf boardgame-app.tar -C boardgame
            cd boardgame

            echo "Building JAR with Maven..."
            chmod +x mvnw
            ./mvnw clean package -DskipTests

            echo "Building Docker image..."
            docker build -t boardgame-app .

            echo "Stopping old container..."
            docker stop boardgame || true
            docker rm boardgame || true

            echo "Running new container..."
            docker run -d --name boardgame -p 8080:8080 boardgame-app

            echo "Deployment complete!"
