# name: Build, Test, Dockerize and Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: temurin
#         java-version: 17

#     - name: Make mvnw executable
#       working-directory: BoardGame-main
#       run: chmod +x ./mvnw

#     - name: Build with Maven
#       working-directory: BoardGame-main
#       run: ./mvnw clean install -DskipTests

#     - name: Build Docker image
#       working-directory: BoardGame-main
#       run: docker build -t boardgame-app .

#     - name: Save Docker image to TAR
#       working-directory: BoardGame-main
#       run: docker save boardgame-app > boardgame-app.tar

#     - name: Copy files to EC2
#       uses: appleboy/scp-action@v0.1.7
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}
#         port: ${{ secrets.EC2_SSH_PORT }}
#         key: ${{ secrets.EC2_SSH_KEY }}
#         source: |
#           BoardGame-main/boardgame-app.tar
#           BoardGame-main/docker-compose.yml
#         target: /home/${{ secrets.EC2_USER }}/app

#     - name: SSH into EC2 and Deploy
#       uses: appleboy/ssh-action@v0.1.10
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}
#         port: ${{ secrets.EC2_SSH_PORT }}
#         key: ${{ secrets.EC2_SSH_KEY }}
#         script: |
#           cd /home/${{ secrets.EC2_USER }}/app
#           docker load < boardgame-app.tar
#           docker compose down || true
#           docker compose up -d



name: Build, Test, Dockerize and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Make mvnw executable
      run: chmod +x ./Boardgame/mvnw

    - name: Build with Maven
      run: ./Boardgame/mvnw clean install -DskipTests

    - name: Build Docker image
      run: docker build -t boardgame-app ./Boardgame

    - name: Save Docker image to TAR
      run: docker save boardgame-app > ./Boardgame/boardgame-app.tar

    - name: Debug files before SCP
      run: |
        pwd
        ls -l Boardgame
        test -f Boardgame/boardgame-app.tar && echo "Docker TAR exists ✅"
        test -f Boardgame/docker-compose.yml && echo "docker-compose.yml exists ✅"

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        port: ${{ secrets.EC2_SSH_PORT }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: |
          Boardgame/boardgame-app.tar
          Boardgame/docker-compose.yml
        target: /home/${{ secrets.EC2_USER }}/app

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        port: ${{ secrets.EC2_SSH_PORT }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/${{ secrets.EC2_USER }}/app
          docker load < boardgame-app.tar
          docker compose down || true
          docker compose up -d



